---

- name: Create ssh config file
  template:
    src: ssh_config.j2
    dest: "/home/{{ spark_user }}/.ssh/config"
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"
    mode: 0600

- name: Set ssh dir and files perms
  file:
    path: /home/{{ spark_master_user }}/.ssh/
    owner: "{{ spark_user }}"
    mode: 0600
    recurse: yes

- name: Set ssh dir perms
  file:
    path: /home/{{ spark_master_user }}/.ssh
    owner: "{{ spark_user }}"
    mode: 0700

# vim: ff=unix:ai:et:sw=2:ts=2:

