---

#- name: Set JAVA HOME
#  lineinfile:
#    dest: "/home/{{ spark_user }}/.bashrc"
#    line: "export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which java)))))"
#    owner: "{{ spark_user }}"
#    group: "{{ spark_user }}"
#    insertafter: 'EOF'
#    create: yes
#    state: present

- name: Set bash profile
  blockinfile:
    block: |
      export PATH
      export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which java)))))
      export PATH=$PATH:$JAVA_HOME/bin
      export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
      #Scala
      export PATH=$PATH:/usr/lib/scala/bin
      #Spark
      export SPARK_EXAMPLES_JAR={{ spark_install_dir }}/spark-{{ spark_version }}/examples/jars/spark-examples_2.11-2.0.0.jar
      export SPARK_HOME={{ spark_install_dir }}/spark-{{ spark_version }}
      export PATH=$PATH:$SPARK_HOME/bin
      export SPARK_LOCAL_IP={{ spark_node_ip }}
      if ! pgrep -u "$USER" ssh-agent > /dev/null; then
        ssh-agent > ~/.ssh-agent-thing
      fi
      if [[ "$SSH_AGENT_PID" == "" ]]; then
        eval "$(<~/.ssh-agent-thing)"
        echo "HOLA"
      fi
    dest: "/home/{{ spark_user }}/.bash_profile"
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"
    insertafter: 'EOF'
    create: yes
    state: present

# vim: ff=unix:ai:et:sw=2:ts=2:
