---

- name: Create ssh config file
  template:
    src: ssh_config.j2
    dest: "/home/{{ hadoop_user }}/.ssh/config"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
    mode: 0600

- name: Set ssh dir and files perms
  file:
    path: /home/{{ hadoop_user }}/.ssh/
    owner: "{{ hadoop_user }}"
    mode: 0600
    recurse: yes

- name: Set ssh dir perms
  file:
    path: /home/{{ hadoop_user }}/.ssh
    owner: "{{ hadoop_user }}"
    mode: 0700

# vim: ff=unix:ai:et:sw=2:ts=2:

