---
- name: Customized spark log4j properties
  template:
    src: "log4j.properties.j2"
    dest: "{{spark_install_dir}}/spark-{{spark_version}}/conf/log4j.properties"
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"
