---

spark_version: "2.2.0-bin-hadoop2.6"
spark_mirror: "https://archive.apache.org/dist/spark/spark-2.2.0"
 
spark_install_dir: "/opt"
spark_log_dir: "/var/log/spark"

spark_master_ip: "192.168.130.148"
#spark_master_user: "usuariomaster"
spark_master_user: "sparkuser"
#spark_master_user_pwd: "usuariomaster1"
spark_master_user_pwd: "sparkuser1"

spark_worker_ip: "192.168.130.150"
#spark_worker_user: "usuarioworker"
spark_worker_user: "sparkuser"
#spark_worker_user_pwd: "usuarioworker1"
spark_worker_user_pwd: "sparkuser1"
spark_worker_cores: "1"
spark_worker_memory: "512M"
#spark_slaves: ["192.168.130.150"]
spark_slaves: ["worker"]

spark_user_groups: []

spark_test_app: true

spark_version: "2.2.0-bin-hadoop2.6"
spark_mirror: "https://archive.apache.org/dist/spark/spark-2.2.0"

spark_install_dir: "/opt"
spark_log_dir: "/var/log/spark"

mesos_test_app: true
