---

- name: "Restart all hadoop from master"
  shell: |
    {{ hadoop_install_dir }}/hadoop-{{ hadoop_version }}/sbin/stop-all.sh
    sleep 20
    {{ hadoop_install_dir }}/hadoop-{{ hadoop_version }}/sbin/start-all.sh
  become: yes
  become_user: "{{ hadoop_user }}"
  ignore_errors: true
  when: ansible_hostname == "master"

# vim: ff=unix:ai:et:sw=2:ts=2:
